### ISSUE TITLE
Boolean incorrectly encoded as NSNumber

### ISSUE THREAD

**Issue by andrewjackman** [edwardaux/Ogra#18]
Although JSON does not have explicit typing, a Boolean value is commonly rendered as one of the two literal values, **true** or **false**. Ogra is encoding it as an NSNumber which results in a number value of **0** or **1** in the resulting JSON.

This seems to be happening because Argo decodes true/false into NSNumber(0) or NSNumber(1), and Ogra is deferring to Argo's .Number(NSNumber(bool:)) to encode Bool values. When rendering back to JSON though, we need to be able to render back to the literal values **true** and **false**.

I'm not sure how you would make this work without Argo also supporting a "case Boolean" in the JSON enum, but I'd be interested to hear your thoughts/suggestions on this issue.

**Comment by paulyoung** [comment]
https://github.com/thoughtbot/Argo/issues/191 seems relevant here.

**Comment by gfontenot** [comment]
I'm interested to know if this is actually an issue. For example, If I did this in Obj-C:

``` objectivec
NSDictionary *foo = @{
  @"boolean": @(YES)
};
```

and then translated that into JSON, you'd end up with the same thing.

The problem here is _essentially_ that Objective-C (and therefore `NSJSONSerialization`) has no object representation of Booleans and so resorts to overloading `NSNumber` (which then trickles down to Argo). As I stated in thoughtbot/Argo#191 we'd _love_ to remove the reliance on `NSNumber` and break out `Boolean` into its own case, but it doesn't seem like it's possible (right now).

**Comment by andrewjackman** [comment]
However, if you insert the literal @YES into the dictionary the behaviour is what I expect.

``` objective-c
NSDictionary *foo = @{
    @"boolean": @YES
};

NSData *jsonData = [NSJSONSerialization dataWithJSONObject:foo options:0 error:nil];
NSString *rendered = [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding];
NSLog(@"JSON:\n%@", rendered);
```

The output is

JSON:
{"boolean":true}

**Comment by gfontenot** [comment]
Well that sent me down a rabbit hole. Learned a lot about NSNumbers today.

This should help: thoughtbot/Argo#314

**Comment by edwardaux** [comment]
Excellent! I'm overseas for another two weeks but will make the appropriate changes to Ogra as soon as I return.

**Comment by andrewjackman** [comment]
Awesome! Thanks @gfontenot

**Comment by edwardaux** [comment]
I've finally managed to get time to do this (in large part, due to @duffpod's PR kicking me into gear). See #21. Feel free to re-open this issue if that doesn't resolve your problem.
