### ISSUE TITLE
Carthage usage

### ISSUE THREAD

**Issue by ruipfcosta** [edwardaux/Ogra#8]
There is a problem with the current instructions for Carthage usage:

``` ruby
github "edwardaux/Ogra"
```

This will use a version of the Cartfile pointing to Argo's branch "td-swift-2" which no longer exists.
I fixed it by specifying master the following on my Cartfile:

``` ruby
github "edwardaux/Ogra" "master"
```

**Comment by edwardaux** [comment]
Hmm... that's really weird. I don't know why carthage is not picking up the latest code from Ogra `master`.  

If I look at the Ogra tags, I see that the latest version is 1.1 - which does point to Argo `td-swift-2` branch. Maybe carthage has some logic that looks for the latest tag and tries to use that instead of the `master` HEAD. 

Investigating now...

**Comment by paulyoung** [comment]
I believe Carthage will use the latest tag, if there is one.

I think the way to fix this is to tag a new release of Ogra (v2 since Argo v2 / Swift v2 is a breaking change)

**Comment by edwardaux** [comment]
Hmm... my google-fu was deserting me, but I eventually found https://github.com/Carthage/Carthage/issues/624#issuecomment-122014234

It certainly matches what we're seeing. I notice that Argo has just release 2.1.0 a few days ago. Once I get home tonight, I'll probably bump up Ogra to point to that, do some quick testing, and then add a 2.1.0 tag to Ogra. Will post back here when I'm done.

**Comment by edwardaux** [comment]
Actually... managed to get a few minutes, and have bumped Ogra up to 2.1.0 inline with the new Argo release.

Thanks for the heads-up... I didn't realise carthage had that behaviour. Let me know if you have any more problems with the latest release.
